### ISSUE TITLE
crash loading into servers

### ISSUE THREAD

**Issue by FullMetalMaster** [Shadows-of-Fire/FastWorkbench#66] opened 2021-01-16 19:02 UTC
at first we thought it was mekanism and OptiFine tripping each other but it seems that your modtripping something in the logs when logging into servers it hard crashes idk why? here the files https://www.mediafire.com/file/0cq085fjpohzgzh/logs_and_the_crash.zip/file

**Comment by FullMetalMaster** [comment] 2021-01-16 19:03
this is 1.16.4 forge lastest btw

**Comment by Shadows-of-Fire** [comment] 2021-01-17 07:27
That crash is coming from mekanism.  There *is* an error in there, but it's the same error as #63 

Duplicate of #63

**Closed as completed by Shadows-of-Fire** 2021-01-17 07:27 UTC
