### ISSUE TITLE
Crafting table doesn't always show output item, but it's still selectable

### ISSUE THREAD

**Issue by Bidgam** [Shadows-of-Fire/FastWorkbench#59] opened 2020-12-14 18:21 UTC
1.16.4, Forge 35.1.4, FastWorkbench-1.1.6.3-4.4.1

Some items like an iron rod from Silent's Gems, but not all items, will not show its icon in the crafting results square, though the ingredients show properly. You can also pick the final item up out of the results square even though it's not visible. Upon placement into your backpack it shows properly.

I'll reply to this is I can nail down if it's a specific other mod's items causing the issue (and thus perhaps their fault).

**Comment by Bidgam** [comment] 2020-12-14 18:27
Confirmed that it doesn't appear to be another mod, at least directly, as the normal crafting of a default minecraft chest still results.

Small note that the item in the output box does flicker for a very brief moment.

**Comment by Shadows-of-Fire** [comment] 2021-01-17 06:37
I want to say this is probably a duplicate of the issue described in #58

**Closed as completed by Shadows-of-Fire** 2021-01-17 06:37 UTC
