### ISSUE TITLE
[1.18.2-6.0.2] Using CTRL+Q to drop all crafted items results in a crash

### ISSUE THREAD

**Issue by Pato05** [Shadows-of-Fire/FastWorkbench#89] opened 2022-08-07 15:58 UTC
* Happens only if the mod is installed on the client side too

**Comment by Shadows-of-Fire** [comment] 2022-08-07 16:30
crash report?

**Comment by Shadows-of-Fire** [comment] 2022-08-11 02:22
Closing as cannot reproduce and due to lack of information.  If you are playing on a server, the server must have this mod installed as well as the client.

**Closed as completed by Shadows-of-Fire** 2022-08-11 02:22 UTC
