### ISSUE TITLE
Invisible items in inventory when switching dimension.

### ISSUE THREAD

**Issue by SzczurekYT** [Shadows-of-Fire/FastWorkbench#64] opened 2021-01-16 09:27 UTC
Mod version: 4.4.1
Forge: 1.16.4 - 35.1.37

I play all the mods 6 modpack, with a few performance mods (mostly optifine), and today I updated my mods and also installed crafttweaker as a dependency of another mod from the mod pack. (I don't know if this is related to a bug) And there was a bug - when I travel to another dimension all items in my inventory become invisible and to fix I have to select and place each item with the mouse.

This thing repeat in log:
https://pastebin.com/5gfA2z9v

Steps to replicate: Download all the mods 6 modpack and update all mods to newest version, change forge to 35.1.37, Install optifine and optiforge. Now issue should show when you change dimension.

Also my game crashed, probably when I put something in my crafting grid on 1.16.4. But this is reported, but I want to say that this also happen in 1.16.4

Sorry for my English

**Comment by coolsimulations** [comment] 2021-01-17 00:25
I have also been experiencing this issued disappearing items but was not able to determine which mod was causing this. Using 1.16.5 forge version 36.0.0.

**Comment by SzczurekYT** [comment] 2021-01-17 06:59
Now I play all of the mods 6 pack without updating mods and it's fine. This is probably incompatibility with another mod.

**Comment by Shadows-of-Fire** [comment] 2021-01-17 07:28
Duplicate of #63

**Closed as completed by Shadows-of-Fire** 2021-01-17 07:28 UTC
