### ISSUE TITLE
[1.14.4] Incompatability With Building Gadgets

### ISSUE THREAD

**Issue by EmosewaPixel** [Shadows-of-Fire/FastWorkbench#23] opened 2019-07-28 12:55 UTC
Well, as crafting tables can't currently be opened to fully test this, I'm going to go by the 3-way interaction with JEI. Simply put, when both Building Gadgets and Fast Workbench are present, JEI completely breaks, yet that doesn't happen when there's only one of the 2 mods. Since it doesn't happen with any other mod, I presume that it more specifically has to do with Building Gadgets' custom crafting recipe type and serializer. If it does, the issue is more of not knowing what needs to be changed to make them work fine together.
In the current version of the mod that looks like this: https://github.com/Direwolf20-MC/BuildingGadgets/blob/653ae52f88fdf2bbf80ba176784ff1bfb5d374b7/src/main/java/com/direwolf20/buildinggadgets/common/config/crafting/RecipeConstructionPaste.java 
Though an extra override has been added since, hoping maybe that would fix it: https://github.com/Direwolf20-MC/BuildingGadgets/blob/a277278733751c412ffbdf41db404b31b71a3e44/src/main/java/com/direwolf20/buildinggadgets/common/config/crafting/RecipeConstructionPaste.java#L35-L38

Relevant issue on Building Gadget's repo: https://github.com/Direwolf20-MC/BuildingGadgets/issues/333

**Comment by Shadows-of-Fire** [comment] 2019-08-05 03:44
Was likely also caused by the object holder bug.  Should be resolved in forge 41+

**Closed by Shadows-of-Fire** 2019-08-05 03:44 UTC
