### ISSUE TITLE
[compatibility] [1.12.2] Blocking ExtraUtilities Unstable Ingot Recipe

### ISSUE THREAD

**Issue by ToMe25** [Shadows-of-Fire/FastWorkbench#5] opened 2018-06-02 06:31 UTC
FastWorkbench is Blocking ExtraUtilities Unstable Ingot Recipe, but it wil be shown in JEI.

With FastWorkbench:
![2018-06-02_08 23 39](https://user-images.githubusercontent.com/38815969/40871605-effe366a-663e-11e8-95c0-54ee019bfe03.png)

Without FastWorkbench:
![2018-06-02_08 26 37](https://user-images.githubusercontent.com/38815969/40871609-fb829fc6-663e-11e8-8f70-9707b0042f25.png)

Enviroment:
MC Version: 1.12.2
Forge Version: 14.23.4.2703
ExtraUtilities2 Version: 1.7.6
FastWorkbench Version: 1.4.0
JEI Version: 4.9.1.188
No Other Mods Loaded.

**Comment by Shadows-of-Fire** [comment] 2018-06-02 06:55
Interesting.  Is there any special nature of that recipe?  If it was just normal it should work as intended...

**Comment by ToMe25** [comment] 2018-06-02 07:03
The Crafted Item explodes after 10 seconds(or when you close the GUI), but i dont know how this Recipe works.

**Comment by Shadows-of-Fire** [comment] 2018-06-02 07:20
I think I should be able to get this done from my side (this took forever to find, xu source is a nightmare) but in the meantime there appears to be a config option labeled `Unstable Ingot: Allowed Classes`, If you want it to work immediately add `shadows.fastbench.gui.ContainerFastBench` and `shadows.fastbench.gui.GuiFastBench$ClientContainerFastBench` to the list.

My fix will just be me forcibly adding to this list in code, and should be done shortly.

**Comment by ToMe25** [comment] 2018-06-02 07:28
THX :)

**Comment by Shadows-of-Fire** [comment] 2018-06-02 07:36
Resolved in 1.5.0

**Closed by Shadows-of-Fire** 2018-06-02 07:36 UTC
