### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by icanlevitateoff** [Shadows-of-Fire/FastWorkbench#97] opened 2023-04-14 12:59 UTC
It seems the latest version of FastWorkbench for 1.19 introduced a little dupe bug,

Steps to replicate:
Right click to craft with only enough items to craft 1 of the item.
It should then craft a stack of the item despite not having enough resources to do so.
This works in either the crafting inventory or the fastworkbench modified vanilla workbench.

**Comment by icanlevitateoff** [comment] 2023-04-17 08:29
This bug can also cause item loss if you have more than enough to craft a stack.

**Comment by Shadows-of-Fire** [comment] 2023-04-20 05:57
Cannot reproduce in isolation in singleplayer or on a dedicated server.

**Comment by Vaelzan** [comment] 2023-04-27 06:28
It's reproducible using Valhelsia 5, v5.0.18, as an extra data point (and was not present in 5.0.17). I don't have time to pinpoint it to a specific mod interaction right now (nor will I for the foreseeable future due to surgery in the morning), so this isn't the most useful information other than that it may help as a starting point if there's anybody else reading this that has time to help narrow it down from there.

**Comment by Shadows-of-Fire** [comment] 2023-04-27 06:40
it has been isolated to be an interaction with crafting tweaks, a fix is in the works

**Comment by Vaelzan** [comment] 2023-04-27 06:41
Thanks, much appreciated!

**Closed as completed** 2023-04-27 08:16 UTC
Labels: cannot reproduce
